import logging

DEFAULT_BROWSER = "chrome"
DEFAULT_OPENCART_BASE_URL = "http://192.168.0.105:8081"
DEFAULT_SELENIUM_DRIVERS_PATH = "~/selenium_drivers/"
DEFAULT_HEADLESS_MODE = False
DEFAULT_EXECUTOR = "192.168.0.105"
DEFAULT_SELENOID_BROWSER_VERSION = "108.0"
DEFAULT_LOGGING_LEVEL = logging.DEBUG

ADMIN_PANEL_CREDENTIALS = ("user", "bitnami")
